apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - max:
        cpu: "1"
        memory: "4Gi"
      min:
        cpu: "15m"
        memory: "64Mi"
      type: Container
