apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: 871866584905.dkr.ecr.eu-central-1.amazonaws.com/aws-eks-intro/hello:0.0.1
          resources:
            requests:
              cpu: "30m"
              memory: "125Mi"
            limits:
              cpu: "60m"
              memory: "250Mi"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
